#!/bin/sh

/usr/bin/qemu-arm-static /bin/sh cp /bin/sh /bin/sh.real
/usr/bin/qemu-arm-static /bin/sh cat <<EOT >> /bin/sh-shim 
#!/usr/bin/qemu-arm-static /bin/sh.real

set -o errexit

cp /bin/sh.real /bin/sh  
/bin/sh "$@"
cp /usr/bin/sh-shim /bin/sh  
EOT

/usr/bin/qemu-arm-static /bin/sh cp /bin/sh-shim  /bin/sh

